---
- hosts: localhost
  connection: local
  tasks:
  - name: Crear grupo de seguridad con HTTPS, HTTP y SSH
    ec2_group:
      name: sg_profe
      vpc_id: vpc-7a117c07
      description: sg con las reglas
      region: us-west-1
      rules:
        - proto: tcp
          ports:
          - 443
          - 80
          - 23
          - 8080
          #Agregar puerto 22 para la conexión con SSH
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: Acepto todo el trafico
  - name: Creamos nuestro servidor
    ec2:
    #La región debe ser la misma que la declarada anteriormente
      region: us-west-1
      instance_type: t2.micro
      image: ami-0c2b8ca1dad447f8a
      instance_tags:
      #En el grupo de seguridad se declaro otro nombre, ambos deben ser iguales
        Name: sg_profe
      wait: yes
      wait_timeout: 500
      group: grupo_creado
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: subnet-82bceedd
      #La IP no es pública, se cambia por YES
      assign_public_ip: yes
      key_name: millave
    register: info
  - name: DNS Publico de nuestro servidor
    debug:
      msg: "La ip publica es {{ info.instances[0].public_ip }} y su DNS es {{ info.instances[0].public_dns_name }}" 